name: t_release
description: app version control system.it will generate release.json file.
version: 0.0.4
repository: https://github.com/ThanCoder/t_release
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  dio: ^5.8.0+1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
